# docker-compose.prod.yml - ChatTrain MVP1 Production Environment
version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/chattrain.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - MAX_TOKENS=${MAX_TOKENS:-200}
      - TEMPERATURE=${TEMPERATURE:-0.7}
      - RATE_LIMIT_REQUESTS_PER_MINUTE=${RATE_LIMIT_REQUESTS_PER_MINUTE:-20}
      - MAX_MESSAGE_LENGTH=${MAX_MESSAGE_LENGTH:-2000}
    volumes:
      - ./content:/app/content
      - chattrain_data:/app/data
    depends_on:
      - database
      - redis
    restart: unless-stopped
    networks:
      - chattrain-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend Service (Production)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - chattrain-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Database Service
  database:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-chattrain}
      - POSTGRES_USER=${POSTGRES_USER:-chattrain}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped
    networks:
      - chattrain-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Redis Service
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - chattrain-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - chattrain-network

volumes:
  chattrain_data:
  postgres_data:
  redis_data:

networks:
  chattrain-network:
    driver: bridge